### PR TITLE
FAI-967: Ability to cache metrics if the dataset hasn't changed

### LINKED ISSUE #89: Ability to cache metrics if the dataset hasn't changed
### Describe the bug

Ability to cache metrics if the dataset hasn't changed

### Expected behavior

_No response_

### Actual behavior

_No response_

### How to Reproduce?

_No response_

### Output of `uname -a` or `ver`

_No response_

### Output of `java -version`

_No response_

### TrustyAI version or git rev

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ruivieira**
Adds a cache layer to metrics request, if neither the requests or data have changed.

Closes #89

### CODE REVIEW

**Review by tteofili — APPROVED** [review]
LGTM

File: explainability-service/src/main/java/org/kie/trustyai/service/data/DataSource.java [hunk 1]
```diff
@@ -30,8 +33,11 @@ public class DataSource {
     @Inject
     ServiceConfig serviceConfig;
 
+    @CacheResult(cacheName = "dataframe", keyGenerator = DataframeCacheKeyGen.class)
     public Dataframe getDataframe() throws DataframeCreateException {
 
+        LOG.info("Cache miss! Reading dataframe");
```
Comment (danielezonca) [inline explainability-service/src/main/java/org/kie/trustyai/service/data/DataSource.java]: I would make it `trace` or keep `info` but adding more context like logging `getLastModified` value
Wdyt?

File: explainability-service/src/main/java/org/kie/trustyai/service/data/cache/MetricCalculationCacheKeyGen.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+@ApplicationScoped
+public class MetricCalculationCacheKeyGen implements CacheKeyGenerator {
+
+    @Inject
+    Instance<Storage> storage;
+
+    @Override
+    public Object generate(Method method, Object... methodParams) {
+        return new CompositeCacheKey(storage.get().getLastModified(), methodParams[1].hashCode());
```
Comment (danielezonca) [inline explainability-service/src/main/java/org/kie/trustyai/service/data/cache/MetricCalculationCacheKeyGen.java]: `methodParams` could be empty. We can decide to fallback to random value to force cache reload in this case or throw an error if it should never happen.
It also makes the assumption (as far as I can see) that the first param is a `DataFrame`.
We might implement a test that uses Jandex to get all method annotated with `CacheResult ` that are using `MetricCalculationCacheKeyGen` to verify that the first parameter exists and is a `DataFrame`.
Wdyt?

Note: feel free to postpone to a future ticket this improvement

File: explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java [hunk 3]
```diff
@@ -63,4 +63,9 @@ public boolean inputExists() throws StorageReadException {
     public boolean outputExists() throws StorageReadException {
         return data.containsKey(config.outputFilename().get());
     }
+
+    @Override
+    public long getLastModified() {
+        return data.get(config.inputFilename().get()).hashCode();
```
Comment (danielezonca) [inline explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java]: I know `MemoryStorage` is mainly for test but this implementation looks wrong

File: explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MinioStorage.java [hunk 4]
```diff
@@ -203,4 +203,9 @@ public boolean inputExists() throws StorageReadException {
     public boolean outputExists() throws StorageReadException {
         return false;
     }
+
+    @Override
+    public long getLastModified() {
+        return isObjectAvailable(bucketName, inputFilename).lastModified().toInstant().toEpochMilli();
```
Comment (danielezonca) [inline explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MinioStorage.java]: What `isObjectAvailable` returns if the value is not available? This code seems not managing that case

File: explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/MockMetricsStorage.java [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+import org.kie.trustyai.service.data.exceptions.StorageReadException;
+import org.kie.trustyai.service.data.exceptions.StorageWriteException;
+import org.kie.trustyai.service.data.storage.Storage;
+
+import io.quarkus.test.Mock;
+
+@Mock
+@Alternative
+@ApplicationScoped
+public class MockMetricsStorage extends Storage {
```
Comment (danielezonca) [inline explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/MockMetricsStorage.java]: This looks an empty mock, have you considered [`InjectMocks` or similar](https://quarkus.io/blog/mocking/#using-quarkusmock) to have a similar behaviour without the need to declare this class?

Comment (ruivieira) [reply explainability-service/src/test/java/org/kie/trustyai/service/endpoints/metrics/MockMetricsStorage.java]: Removed

File: explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MinioStorage.java (hunk 4 above)
Comment (ruivieira) [reply explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MinioStorage.java]: If the object is not available, it will now throw a random value (forcing a cache miss and going through the proper flow of handling missing data files)

File: explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java (hunk 3 above)
Comment (ruivieira) [reply explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java]: For the memory case (where a "file" is a String), I'll assume that the modification logic could be calculating a checksum of the String (defaulted to CRC32). wdyt?

File: explainability-service/src/main/java/org/kie/trustyai/service/data/cache/MetricCalculationCacheKeyGen.java (hunk 2 above)
Comment (ruivieira) [reply explainability-service/src/main/java/org/kie/trustyai/service/data/cache/MetricCalculationCacheKeyGen.java]: @danielezonca thanks. discussed offline.

File: explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java (hunk 3 above)
Comment (danielezonca) [reply explainability-service/src/main/java/org/kie/trustyai/service/data/storage/MemoryStorage.java]: LGTM :)

**Review by danielezonca — APPROVED** [review]
